name: docs

on: [push]

env:
  PLUGIN_NAME: auto-session

jobs:
  docs:
    runs-on: ubuntu-latest
    name: panvimdoc
    steps:
      - uses: actions/checkout@v4

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.3

      - name: Update README with config sections
        run: nvim --clean --headless -l scripts/update_readme.lua

      - name: Create /doc
        run: mkdir -p doc
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim"
          demojify: true
          treesitter: true
          shiftheadinglevelby: -1

      - name: Ignore if only date changed
        run: |
          changed_files=$(git diff --name-only doc/*.txt || true)
          for f in $changed_files; do
            # Skip if file no longer exists (deleted?)
            if [ ! -f "$f" ]; then continue; fi
            # If it's onle the first line that changed (i.e. date), drop the change
            if diff -q <(tail -n +2 "$f") <(tail -n +2 <(git show HEAD:"$f")) >/dev/null; then
              echo "Only date line changed in $f, restoring from HEAD."
              git restore "$f"
            fi
          done

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate docs"
          file_pattern: "doc/*.txt README.md"
