name: docs

on: [push]

env:
  PLUGIN_NAME: auto-session

jobs:
  docs:
    runs-on: ubuntu-latest
    name: emmylua to vimdoc
    steps:
      - uses: actions/checkout@v4

      - name: setup neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.11.3

      - name: Update README with config sections
        run: nvim --clean --headless -l scripts/update_readme.lua

      - name: Create /doc
        run: mkdir -p doc
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: ${{ github.event.repository.name }}
          version: "Neovim"
          demojify: true
          treesitter: true

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate docs"
          file_pattern: "doc/*.txt README.md"
